### ISSUE TITLE
Client implementation in the GnatMQ nuget package does not work

### ISSUE THREAD

**Issue by mikkorepolainen** [ppatierno/gnatmq#3]
When using the client `uPLibrary.Networking.M2Mqtt.MqttClient` from the GnatMQ nuget package, the Connect method always throws the following exception. Using the same code with the M2Mqtt nuget package works flawlessly.
```
Exception of type 'uPLibrary.Networking.M2Mqtt.Exceptions.MqttCommunicationException' was thrown.
   at uPLibrary.Networking.M2Mqtt.MqttClient.SendReceive(Byte[] msgBytes, Int32 timeout) in c:\Users\ppatierno\Source\Repos\gnatmq\GnatMQ\MqttClient.cs:line 1089
   at uPLibrary.Networking.M2Mqtt.MqttClient.SendReceive(MqttMsgBase msg, Int32 timeout) in c:\Users\ppatierno\Source\Repos\gnatmq\GnatMQ\MqttClient.cs:line 1114
   at uPLibrary.Networking.M2Mqtt.MqttClient.SendReceive(MqttMsgBase msg) in c:\Users\ppatierno\Source\Repos\gnatmq\GnatMQ\MqttClient.cs:line 1100
   at uPLibrary.Networking.M2Mqtt.MqttClient.Connect(String clientId, String username, String password, Boolean willRetain, Byte willQosLevel, Boolean willFlag, String willTopic, String willMessage, Boolean cleanSession, UInt16 keepAlivePeriod) in c:\Users\ppatierno\Source\Repos\gnatmq\GnatMQ\MqttClient.cs:line 564
   at uPLibrary.Networking.M2Mqtt.MqttClient.Connect(String clientId) in c:\Users\ppatierno\Source\Repos\gnatmq\GnatMQ\MqttClient.cs:line 475
```

**Comment by ppatierno** [comment]
You can't use the MqttClient class as client if you are using the GnatMQ package. The MqttClient class is used inside the broker for handling remote client but isn't usable as client itself outside the broker.
You need to use the M2Mqtt project.

Paolo.

**Comment by mikkorepolainen** [comment]
Hi. The problem with this solution is that the client classes are in the same namespace and therefore I cannot reference both the broker and the client packages in the same project in order to build a single-assembly MQTT bridge to another medium using these packages.
I'll appreciate suggestions for a better way to build such a bridge.

**Comment by ppatierno** [comment]
Yes I know about this issue.
Using both projects in the same solution is one of the future feature.
I'll try to deep into it as soon as possible.

Paolo.

**Comment by nkostis** [comment]
as an fyi: What we (tentatively) did to solve this very issue was download the M2MQTT project source code, change namespaces for the client and rebuild it.

**Comment by mikkorepolainen** [comment]
I switched to the nmqtt client instead. As an afterthought, would it make any sense to have a mechanism to subscribe to messages on the broker's interface for applications like this? It's the first place I looked intuitively.

**Comment by ppatierno** [comment]
Pay attention that nmqtt was update 2 years ago ... I don't think it supports the latest OASIS MQTT 3.1.1 specification.

**Comment by rameshpucha** [comment]
Hi Paolo,
I am getting this following issue.I am new to Mqtt Broker please help.

   at uPLibrary.Networking.M2Mqtt.MqttClient.SendReceive(Byte[] msgBytes, Int32 timeout) in c:\Users\ppatierno\Source\Repos\m2mqtt\M2Mqtt\MqttClient.cs:line 1094
   at uPLibrary.Networking.M2Mqtt.MqttClient.SendReceive(MqttMsgBase msg, Int32 timeout) in c:\Users\ppatierno\Source\Repos\m2mqtt\M2Mqtt\MqttClient.cs:line 1117
   at uPLibrary.Networking.M2Mqtt.MqttClient.Connect(String clientId, String username, String password, Boolean willRetain, Byte willQosLevel, Boolean willFlag, String willTopic, String willMessage, Boolean cleanSession, UInt16 keepAlivePeriod) in c:\Users\ppatierno\Source\Repos\m2mqtt\M2Mqtt\MqttClient.cs:line 567
   at uPLibrary.Networking.M2Mqtt.MqttClient.Connect(String clientId, String username, String password, Boolean cleanSession, UInt16 keepAlivePeriod) in c:\Users\ppatierno\Source\Repos\m2mqtt\M2Mqtt\MqttClient.cs:line 512
   at ServicesTest.BrokerWorks.btnCoonect_Click(Object sender, EventArgs e) in D:\R_Working\WattSwot\ServicesTest\BrokerWorks.cs:line 71
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at ServicesTest.Program.Main() in D:\R_Working\WattSwot\ServicesTest\Program.cs:line 19
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Thank you.
